on:
  workflow_dispatch: # Workflow can be manually triggered
  schedule: # Workflow will run on a cron schedule
  - cron: '0 */12 * * *' # Run every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # Caches the pip dependencies to speed up the workflow

      - name: Cache Python dependencies
        id: cache-python-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache-python-deps.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Install Browser
        run: playwright install chromium

      - name: Run script
        env: # This step uses the secrets stored in the GitHub repository's settings
            GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
            TYPE: ${{ secrets.TYPE }}
            PROJECT_ID: ${{ secrets.PROJECT_ID }}
            PROJECT_KEY_ID: ${{ secrets.PROJECT_KEY_ID }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            AUTH_URI: ${{ secrets.AUTH_URI }}
            TOKEN_URI: ${{ secrets.TOKEN_URI }}
            AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
            CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
            UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
            GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
        run: python main.py --gs