on:
  workflow_dispatch: # This workflow can be manually triggered using the GitHub Actions tab
  schedule: # This workflow will run on a cron schedule
  - cron: '0 */12 * * *' # This workflow will run every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest # This workflow will run on the ubuntu-latest machine
    steps:
      - name: Checkout code # This step checks out a copy of your repository on the ubuntu-latest machine
        uses: actions/checkout@v4

      - name: Set up Python # This step sets up Python on the ubuntu-latest machine
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # This caches the pip dependencies to speed up the workflow

      - name: Install dependencies # This step installs all dependencies
        run: pip install -r requirements.txt

      - name: Install Browser # This step installs the browser
        run: playwright install chromium

      - name: Get env # This step runs the script
        run: |
          echo "GOOGLE_SPREADSHEET_ID=$GOOGLE_SPREADSHEET_ID" >> .env
          echo "TYPE=$TYPE" >> .env
          echo "PROJECT_ID=$PROJECT_ID" >> .env
          echo "PROJECT_KEY_ID=$PROJECT_KEY_ID" >> .env
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> .env
          echo "CLIENT_EMAIL=$CLIENT_EMAIL" >> .env
          echo "CLIENT_ID=$CLIENT_ID" >> .env
          echo "AUTH_URI=$AUTH_URI" >> .env
          echo "TOKEN_URI=$TOKEN_URI" >> .env
          echo "AUTH_PROVIDER_X509_CERT_URL=$AUTH_PROVIDER_X509_CERT_URL" >> .env
          echo "CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL" >> .env
          echo "UNIVERSE_DOMAIN=$UNIVERSE_DOMAIN" >> .env
          
      - name: Run script # This step runs the script
        run: python main.py --gs